.PHONY:compile
compile:
	g++ -c test.cpp
.PHONY:link
link:
	g++ -o timer_test timer_test.o
.PHONY:clean
clean:
	rm timer_test.o timer_test
.PHONY:run
run:
	make compile
	make link
	./timer_test